name: SCA Resolver Example

on:
  push:
    branches:
      [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download SCA Resolver
        run: |
          wget https://sca-downloads.s3.amazonaws.com/cli/latest/ScaResolver-linux64.tar.gz
          tar -xzvf ScaResolver-linux64.tar.gz
          rm -rf ScaResolver-linux64.tar.gz

      - name: Install Maven and NPM
        run: |
          sudo apt-get update -y
          sudo apt-get install -y maven npm

      - name: Verify Maven and NPM Versions
        run: |
          echo "Checking Maven version..."
          if command -v mvn >/dev/null 2>&1; then
            mvn -version
          else
            echo "Maven is NOT installed."
            exit 1
          fi

          echo ""
          echo "Checking NPM version..."
          if command -v npm >/dev/null 2>&1; then
            npm -v
            node -v
          else
            echo "NPM is NOT installed."
            exit 1
          fi

      - name: Run Checkmarx One CLI Scan
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          /home/linuxbrew/.linuxbrew/bin/brew install checkmarx/ast-cli/ast-cli
          /home/linuxbrew/.linuxbrew/Cellar/ast-cli/*/bin/cx \
            scan create \
            -s . \
            --agent GitHub \
            --project-name ${{ github.repository }} \
            --branch ${GITHUB_REF##*/} \
            --base-uri ${{ secrets.CX_BASE_URI }} \
            --tenant ${{ secrets.CX_TENANT }} \
            --client-id ${{ secrets.CX_CLIENT_ID }} \
            --client-secret ${{ secrets.CX_CLIENT_SECRET }} \
            --sca-resolver ./ScaResolver
